Code Review editado
tvinente/rede-alimenta pull request #38
Opened 2023-12-20 20:21 UTC by tvinente

Texto do campo Code Review foi editado.

2023-12-20 22:36 UTC, DChrispim requested changes

2023-12-20 22:36 UTC, DChrispim commented on README.md
> +- Na ausência de inconsistências, aprova e realiza merge.
Poderia adicionar que a branch mergiada vai ser deletada depois, mas não é necessário.

2023-12-21 22:17 UTC, tvinente commented on README.md
> +- Na ausência de inconsistências, aprova e realiza merge.
farei.

2023-12-22 01:00 UTC, DChrispim approved these changes

2023-12-22 01:00 UTC, merged